# Generated by Django 5.0.6 on 2025-07-24 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fundamentals", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="filing",
            name="company",
        ),
        migrations.RemoveField(
            model_name="valuationjob",
            name="company",
        ),
        migrations.AddField(
            model_name="filing",
            name="ticker",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="valuationjob",
            name="ticker",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.DeleteModel(
            name="Company",
        ),
    ]
